/**
 * Extracts only the icons listed in ICON_NAMES from the installed Iconify
 * collections into `lib/icons/generated.ts`.
 *
 * Why: the runtime @iconify/react component fetches each glyph from the Iconify
 * API on the client, which ships JS and flashes empty boxes on first paint.
 * Baking the SVG bodies in at build time lets <AppIcon /> stay a Server
 * Component that emits inline SVG - no client bundle, no request, no flash.
 *
 * Run with: pnpm icons
 */
import { writeFileSync } from "node:fs";
import { getIconData, iconToSVG } from "@iconify/utils";

import lucide from "@iconify-json/lucide/icons.json" with { type: "json" };
import logos from "@iconify-json/logos/icons.json" with { type: "json" };

const collections = { lucide, logos };

// Keep in sync with the `icons` map in components/ui/app-icon.tsx.
const ICON_NAMES = [
  "lucide:layout-grid",
  "lucide:package",
  "lucide:shopping-cart",
  "lucide:users",
  "lucide:settings",
  "lucide:life-buoy",
  "lucide:message-circle",
  "lucide:search",
  "lucide:bell",
  "lucide:history",
  "lucide:circle-user-round",
  "lucide:list-filter",
  "lucide:download",
  "lucide:plus",
  "lucide:chevron-left",
  "lucide:chevron-right",
  "lucide:chevron-down",
  "lucide:menu",
  "lucide:more-vertical",
  "lucide:x",
  "lucide:eye",
  "lucide:eye-off",
  "lucide:triangle-alert",
  "lucide:trending-up",
  "lucide:box",
  "lucide:receipt-text",
  "lucide:truck",
  "lucide:wallet",
  "lucide:panel-left",
  "lucide:compass",
  "lucide:log-out",
  "lucide:loader",
  "logos:google-icon",
];

const entries = ICON_NAMES.map((full) => {
  const [prefix, name] = full.split(":");
  const collection = collections[prefix];
  if (!collection) throw new Error(`Unknown icon collection: ${prefix}`);

  const data = getIconData(collection, name);
  if (!data) throw new Error(`Icon not found: ${full}`);

  const { body, attributes } = iconToSVG(data, { height: "none" });
  return [full, { body, viewBox: attributes.viewBox }];
});

const file = `// GENERATED by scripts/build-icons.mjs - do not edit by hand.
// Regenerate with \`pnpm icons\` after changing the icon list.

export interface IconData {
  body: string;
  viewBox: string;
}

export const iconData = ${JSON.stringify(Object.fromEntries(entries), null, 2)} satisfies Record<string, IconData>;

export type IconName = keyof typeof iconData;
`;

writeFileSync(new URL("../lib/icons/generated.ts", import.meta.url), file);
console.log(`Wrote ${entries.length} icons to lib/icons/generated.ts`);
